server.port: 8081

spring:
  application.name: ultunnel-admin-panel

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ultunnel_admin_panel}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

auth:
  login: ${AUTH_LOGIN:admin}
  password: ${AUTH_PASSWORD:admin}